[package]
name = "compiler-rust"
version = "0.0.1"
edition = "2021"
authors = ["Riwan Coëffic"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmi = "0.11.0"
wasm-encoder = "0.3"
wasmprinter = "0.2.0"
pretty_assertions = "1.2.1"
